### ISSUE TITLE
Research if/how we can claim "Learn to Code" name

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/leadership#17]
To get its domain and social media profiles, if possible! Including:
- LearnToCode.com (currently redirects to codeschool)
- LearnToCode.org (currently parked and not being used)
- Facebook.com/learntocode(belongs to some entity based in Las Vegas, Nevada with http://YouCanCode.online/)
- Twitter.com/learntocode (taken, but an unused account)
- GitHub.com/learntocode (taken, but an unused account)
- YouTube.com/learntocode (taken, but an unused account)
- Instagram.com/learntocode (taken, but an unused account)

Possible bad news:
- Learn to Code Inc is a 501c3 nonprofit registered in Oklahoma (https://www.nonprofitstorm.com/learn-to-code-inc_in_74063) with an awful website, http://www.learntocodeok.org/
- "Learn to Code. Change the World" is owned by thecoderschool.com
- "code-to-learn" trademark is owned by the Code-to-Learn Foundation, and codetolearn.org redirects to scratchfoundation.org

**Comment by TheBeege** [comment]
getprogramming.org was open, and I grabbed it. According to https://www.sec.gov/edgar/searchedgar/companysearch.html, there are no companies named Get Programming.
According to http://tmsearch.uspto.gov/bin/gate.exe?f=tess&state=4806:7me383.1.1, Get Programming also has no marks on it. 
I think it's a viable, descriptive name, but re-branding would be a pain. Thoughts?

**Comment by TheBeege** [comment]
https://www.google.com/trends/explore?q=learn%20programming,learn%20to%20code,get%20programming
Learn programming seems to be the heavy hitter. Good news is that learnprogramming.io appears to be open.

According to the US Patent and Trademark Office, "learn programming" has no marks on it.

I'm realizing we may not want to place terribly much value on having a heavy-hitting name right out the gate, since codecademy and whatnot show up as similar terms in Google. If we do good work, whatever we decide to name ourselves may rise up on its own merit.

**Comment by LearningNerd** [comment]
Closing this issue because I think we've confirmed it would cost too much time and/or money to fight this :( Better to just change our name to something we can claim, and this way we can pick something less generic too. I see it as a win-win. Better to change the name now while our group is still young than to wait until later when it'll be a huge hassle.
